global_costmap:
   global_frame: odom         ## 绘制代价地图的坐标系
   robot_base_frame: base  # 机器人本体坐标系
   update_frequency: 5.0      ## 地图更新频率
   publish_frequency: 3.0  # 地图可视化频率
   static_map: false          ## 是否有预先生成好的地图初始化
   rolling_window: true       ## 是否使用滚动窗口，使机器人保持在地图中央
   resolution: 0.05  # 地图分辨率
   transform_tolerance: 1.0   # 允许位置误差
   map_type: costmap # 地图类型